/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Sistema_ristorante;

import javax.swing.JFrame;

/**
 *
 * @author VITO
 */
public class ChiSiamo extends javax.swing.JFrame {

    /**
     * Creates new form ChiSiamo_Form
     */
    public ChiSiamo() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
        setExtendedState( JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_titolo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_ind = new javax.swing.JLabel();
        jLabel_indir = new javax.swing.JLabel();
        jLabel_cell = new javax.swing.JLabel();
        jLabel_num = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_info = new javax.swing.JTextArea();
        jButton_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\location.jpg")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 90, 800, 427);

        jLabel_titolo.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel_titolo.setForeground(new java.awt.Color(255, 153, 153));
        jLabel_titolo.setText("\"SI CUCINA SEMPRE PENSANDO A QUALCUNO ALTRIMENTI STAI SOLO PREPARANDO DA MANGIARE\"");
        jPanel2.add(jLabel_titolo);
        jLabel_titolo.setBounds(180, 30, 1310, 21);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 852, 0, 0);

        jLabel_ind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ind.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_ind.setText("Indirizzo");
        jPanel2.add(jLabel_ind);
        jLabel_ind.setBounds(750, 600, 89, 17);

        jLabel_indir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_indir.setText("Via Alessandro Manzoni,51 Villa Castelli(BR)");
        jPanel2.add(jLabel_indir);
        jLabel_indir.setBounds(880, 600, 292, 20);

        jLabel_cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cell.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_cell.setText("Cell");
        jPanel2.add(jLabel_cell);
        jLabel_cell.setBounds(780, 650, 71, 17);

        jLabel_num.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_num.setText("328/4585129");
        jPanel2.add(jLabel_num);
        jLabel_num.setBounds(890, 640, 282, 27);

        jTextArea_info.setEditable(false);
        jTextArea_info.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea_info.setColumns(20);
        jTextArea_info.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        jTextArea_info.setRows(5);
        jTextArea_info.setText("Siamo lieti di darvi il benvenuto in Limited\nEvent.Il nostro ristorante,seppur piccolo,\nsin dalla sua fondazione avvenuta nel 2012,\nsi afferma per la qualità offerta e per la \ncortesia del suo personale.\nLa nostra cucina rappresenta un viaggio tra i \nsapori tipici pugliesi.\nIl ristorante Limited Event si trova nel\ncentro storico di Villa Castelli,facilmente\nraggiungibile a piedi o con l'auto.\nCosa aspetti a venirci a trovare?\nTroverai cordialità mista a una soddisfacente\ne accurata selezione dei prodotti.\nTi aspettiamo!\n\n");
        jTextArea_info.setAutoscrolls(false);
        jTextArea_info.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), null, null));
        jTextArea_info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextArea_info.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea_info);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 440, 420);

        jButton_home.setBackground(new java.awt.Color(204, 204, 204));
        jButton_home.setForeground(new java.awt.Color(153, 153, 153));
        jButton_home.setText("TORNA ALLA PAGINA PRINCIPALE");
        jButton_home.setActionCommand("");
        jButton_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_homeMouseClicked(evt);
            }
        });
        jPanel2.add(jButton_home);
        jButton_home.setBounds(10, 600, 240, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1900, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_homeMouseClicked
            Main_Page mainform = new Main_Page();
            mainform.setVisible(true);
            mainform.pack();
            mainform.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jButton_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiSiamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiSiamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiSiamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiSiamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiSiamo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_home;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_cell;
    private javax.swing.JLabel jLabel_ind;
    private javax.swing.JLabel jLabel_indir;
    private javax.swing.JLabel jLabel_num;
    private javax.swing.JLabel jLabel_titolo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_info;
    // End of variables declaration//GEN-END:variables
}
