/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Sistema_ristorante;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VITO
 */
public class Elenco_Prenotazioni extends javax.swing.JFrame {

    /**
     * Creates new form ManageClientsForm
     */
    public Elenco_Prenotazioni() {
        initComponents();
        mostra_elenco();
    }
    
    private void mostra_elenco(){
    
        try{
            
           Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/restaurant","root","");
             Statement st = con.createStatement();
              String sql = "select * from prenotazioni";
             ResultSet rs = st.executeQuery(sql);
              
              
             while(rs.next()){
                 String nome = rs.getString("NOME");
                 String cognome = rs.getString("COGNOME");
                 String data = rs.getString("DATA_EVENTO");
                 String tipo = rs.getString("TIPO_EVENTO");
                 String svlg = rs.getString("SVOLGIMENTO_EVENTO");
                 String persone = rs.getString("NUMERO_PERSONE");
                 String cell = rs.getString("RECAPITO_TELEFONICO");
              
                 String tb[] = {nome,cognome,data,tipo,svlg,persone,cell};
                 DefaultTableModel tblModel = (DefaultTableModel)t_prenotazioni.getModel();
                 tblModel.addRow(tb);

      
             } 
              
              
        }
        catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex);  
        }
       
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_prenotazioni = new javax.swing.JTable();
        jLabel_titolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_prenotazioni.setBackground(new java.awt.Color(204, 204, 255));
        t_prenotazioni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_prenotazioni.setFont(new java.awt.Font("Segoe UI Historic", 0, 10)); // NOI18N
        t_prenotazioni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "cognome", "data_evento", "tipo_evento", "svolgimento_evento", "numero_persone", "recapito_telefonico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_prenotazioni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        t_prenotazioni.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jScrollPane1.setViewportView(t_prenotazioni);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1920, 940));

        jLabel_titolo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_titolo.setForeground(new java.awt.Color(102, 51, 255));
        jLabel_titolo.setText("LISTA PRENOTAZIONI LIMITED EVENT");
        getContentPane().add(jLabel_titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 727, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elenco_Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elenco_Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elenco_Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elenco_Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elenco_Prenotazioni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_titolo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_prenotazioni;
    // End of variables declaration//GEN-END:variables
}
