/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Sistema_ristorante;

import javax.swing.JFrame;

/**
 *
 * @author VITO
 */
public class Piatti extends javax.swing.JFrame {

    /**
     * Creates new form Piatti_Form
     */
    public Piatti() {
        initComponents();
        setExtendedState( JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_antip = new javax.swing.JLabel();
        jLabel_friselle = new javax.swing.JLabel();
        jLabel_salumi = new javax.swing.JLabel();
        jButton_HOME = new javax.swing.JButton();
        jLabel_antipasti = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_primi = new javax.swing.JLabel();
        jLabel_orecchiette = new javax.swing.JLabel();
        jLabel_lasagna = new javax.swing.JLabel();
        jLabel_rape = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_secondi = new javax.swing.JLabel();
        jLabel_frittura = new javax.swing.JLabel();
        jLabel1_involtini = new javax.swing.JLabel();
        jLabel_cozze = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_dessert = new javax.swing.JLabel();
        jLabel_tiramisu = new javax.swing.JLabel();
        jLabel_pasticciotto = new javax.swing.JLabel();
        jLabel_monache = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_antip.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_antip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_antip.setText("PIATTI ANTIPASTO");
        jPanel1.add(jLabel_antip, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, 126, -1));

        jLabel_friselle.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\frisella.jpg")); // NOI18N
        jPanel1.add(jLabel_friselle, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 214));

        jLabel_salumi.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\salumi.jpg")); // NOI18N
        jLabel_salumi.setPreferredSize(null);
        jPanel1.add(jLabel_salumi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 1383, 240));

        jButton_HOME.setBackground(new java.awt.Color(204, 204, 204));
        jButton_HOME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_HOME.setForeground(new java.awt.Color(102, 102, 102));
        jButton_HOME.setText("TORNA ALLA PAGINA PRINCIPALE");
        jButton_HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_HOMEMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel_antipasti.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\antipasti.jpg")); // NOI18N
        jPanel1.add(jLabel_antipasti, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 259));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel_primi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_primi.setText("PRIMI PIATTI");

        jLabel_orecchiette.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\orecchiette.jpg")); // NOI18N

        jLabel_lasagna.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\lasagna.jpg")); // NOI18N

        jLabel_rape.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\rape.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel_primi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332)
                .addComponent(jLabel_orecchiette, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel_lasagna)
                .addGap(65, 65, 65)
                .addComponent(jLabel_rape, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel_primi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_orecchiette)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_rape)
                                .addComponent(jLabel_lasagna)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 1920, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel_secondi.setBackground(new java.awt.Color(255, 255, 153));
        jLabel_secondi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_secondi.setText("SECONDI PIATTI");

        jLabel_frittura.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\frittura.jpg")); // NOI18N

        jLabel1_involtini.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\involtini.jpg")); // NOI18N

        jLabel_cozze.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\cozze.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel_secondi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(jLabel_frittura, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel1_involtini, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jLabel_cozze, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel_secondi))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_frittura)
                            .addComponent(jLabel_cozze)
                            .addComponent(jLabel1_involtini))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 554, 1920, -1));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        jLabel_dessert.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_dessert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_dessert.setText("DESSERT");

        jLabel_tiramisu.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\tiramisu.jpg")); // NOI18N

        jLabel_pasticciotto.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\pasticciotto.jpg")); // NOI18N

        jLabel_monache.setIcon(new javax.swing.ImageIcon("C:\\Users\\VITO\\Desktop\\Vanessa progetto\\monache.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel_dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jLabel_tiramisu, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(jLabel_pasticciotto, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239)
                .addComponent(jLabel_monache, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel_dessert))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_monache, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_pasticciotto)
                                .addComponent(jLabel_tiramisu)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 867, 1920, -1));

        getAccessibleContext().setAccessibleParent(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_HOMEMouseClicked
        Main_Page mainform = new Main_Page();
        mainform.setVisible(true);
        mainform.pack();
        mainform.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_HOMEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piatti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HOME;
    private javax.swing.JLabel jLabel1_involtini;
    private javax.swing.JLabel jLabel_antip;
    private javax.swing.JLabel jLabel_antipasti;
    private javax.swing.JLabel jLabel_cozze;
    private javax.swing.JLabel jLabel_dessert;
    private javax.swing.JLabel jLabel_friselle;
    private javax.swing.JLabel jLabel_frittura;
    private javax.swing.JLabel jLabel_lasagna;
    private javax.swing.JLabel jLabel_monache;
    private javax.swing.JLabel jLabel_orecchiette;
    private javax.swing.JLabel jLabel_pasticciotto;
    private javax.swing.JLabel jLabel_primi;
    private javax.swing.JLabel jLabel_rape;
    private javax.swing.JLabel jLabel_salumi;
    private javax.swing.JLabel jLabel_secondi;
    private javax.swing.JLabel jLabel_tiramisu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
