/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Sistema_ristorante;


import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author VITO
 */
public class Prenotazioni extends javax.swing.JFrame {

    /**
     * Creates new form Prenotazioni_Form
     */
    public Prenotazioni() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState( JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jTextField_Fullname = new javax.swing.JTextField();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_cognome = new javax.swing.JLabel();
        jTextField_cognome = new javax.swing.JTextField();
        jLabel_cell = new javax.swing.JLabel();
        jButton_Prenotazione = new javax.swing.JButton();
        jLabel_data = new javax.swing.JLabel();
        jLabel_numero_pers = new javax.swing.JLabel();
        jTextField_num = new javax.swing.JTextField();
        jTextField_cell = new javax.swing.JTextField();
        jTextField_data = new javax.swing.JTextField();
        jLabel_tipo_evento = new javax.swing.JLabel();
        combo_evento = new javax.swing.JComboBox<>();
        jButton_pagina_home = new javax.swing.JButton();
        jLabel_svolg_ev = new javax.swing.JLabel();
        combo_ev = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_title.setText("LIMITED EVENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(664, 664, 664)
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 1920, -1));
        jPanel1.add(jTextField_Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 278, 39));

        jLabel_nome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_nome.setText("Nome");
        jPanel1.add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 200, 48));

        jLabel_cognome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_cognome.setText("Cognome");
        jPanel1.add(jLabel_cognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 216, 33));
        jPanel1.add(jTextField_cognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 278, 39));

        jLabel_cell.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_cell.setText("Recapito telefonico");
        jPanel1.add(jLabel_cell, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 250, 39));

        jButton_Prenotazione.setBackground(new java.awt.Color(51, 204, 0));
        jButton_Prenotazione.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jButton_Prenotazione.setForeground(new java.awt.Color(0, 102, 0));
        jButton_Prenotazione.setText("INSERISCI LA TUA PRENOTAZIONE ");
        jButton_Prenotazione.setMaximumSize(new java.awt.Dimension(107, 37));
        jButton_Prenotazione.setMinimumSize(new java.awt.Dimension(107, 37));
        jButton_Prenotazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrenotazioneActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Prenotazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 700, 450, 45));

        jLabel_data.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_data.setText("Data evento");
        jPanel1.add(jLabel_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 28));

        jLabel_numero_pers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_numero_pers.setText("Numero persone");
        jPanel1.add(jLabel_numero_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 216, 30));
        jPanel1.add(jTextField_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 278, 39));

        jTextField_cell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_cellKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_cell, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 278, 39));
        jPanel1.add(jTextField_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 278, 39));

        jLabel_tipo_evento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_tipo_evento.setText("Tipo evento");
        jPanel1.add(jLabel_tipo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        combo_evento.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        combo_evento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compleanno", "Battesimo", "Comunione", "Cresima", "Laurea", "Matrimonio", "No evento" }));
        combo_evento.setToolTipText("");
        jPanel1.add(combo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 278, 39));

        jButton_pagina_home.setBackground(new java.awt.Color(153, 153, 153));
        jButton_pagina_home.setText(">> TORNA ALLA PAGINA PRINCIPALE");
        jButton_pagina_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_pagina_homeMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_pagina_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 770, -1, -1));

        jLabel_svolg_ev.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_svolg_ev.setText("Svolgimento evento");
        jPanel1.add(jLabel_svolg_ev, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 250, -1));

        combo_ev.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        combo_ev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pranzo", "Cena" }));
        jPanel1.add(combo_ev, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 279, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PrenotazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrenotazioneActionPerformed

        String nome = jTextField_Fullname.getText();
        String cognome = jTextField_cognome.getText();
        String data = jTextField_data.getText();
        String tipo = combo_evento.getSelectedItem().toString();
        String svolg = combo_ev.getSelectedItem().toString();
        String numero = jTextField_num.getText();
        String rec_tel = jTextField_cell.getText();
        
       

        PreparedStatement ps;
        ResultSet rs;
        String query = "INSERT INTO prenotazioni(nome,cognome,data_evento,tipo_evento,svolgimento_evento,numero_persone,recapito_telefonico)" + "VALUES (?,?,?,?,?,?,?)";

        try{
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1,nome);
            ps.setString(2,cognome);
            ps.setString(3,data);
            ps.setString(4,tipo);
            ps.setString(5,svolg);
            ps.setString(6,numero);
            ps.setString(7,rec_tel);

            if(ps.executeUpdate()!= 0){
                JOptionPane.showMessageDialog(null,"La tua prenotazione è stata aggiunta con successo,a breve sarai contattato per sapere la disponibilità o meno della sala per la data del tuo evento");

            }else{
                JOptionPane.showMessageDialog(null,"Errore : Controlla i tuoi dati");

            }
        }catch(SQLException ex){
            Logger.getLogger(Registrazione.class.getName()).log(Level.SEVERE,null,ex);
        }

    }//GEN-LAST:event_jButton_PrenotazioneActionPerformed

    private void jTextField_cellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cellKeyTyped
       //allow only numbers
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
                
    }//GEN-LAST:event_jTextField_cellKeyTyped

    private void jButton_pagina_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_pagina_homeMouseClicked
            Main_Page mainform = new Main_Page();
            mainform.setVisible(true);
            mainform.pack();
            mainform.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jButton_pagina_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prenotazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prenotazioni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_ev;
    private javax.swing.JComboBox<String> combo_evento;
    private javax.swing.JButton jButton_Prenotazione;
    private javax.swing.JButton jButton_pagina_home;
    private javax.swing.JLabel jLabel_cell;
    private javax.swing.JLabel jLabel_cognome;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_numero_pers;
    private javax.swing.JLabel jLabel_svolg_ev;
    private javax.swing.JLabel jLabel_tipo_evento;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Fullname;
    private javax.swing.JTextField jTextField_cell;
    private javax.swing.JTextField jTextField_cognome;
    private javax.swing.JTextField jTextField_data;
    private javax.swing.JTextField jTextField_num;
    // End of variables declaration//GEN-END:variables
}
