/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Sistema_ristorante;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author VITO
 */
public class Registrazione extends javax.swing.JFrame  {

    /**
     * Creates new form Registrazione_Form
     */
    public Registrazione() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
        setExtendedState( JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_titolo = new javax.swing.JLabel();
        jTextField_Fullname = new javax.swing.JTextField();
        jLabel_full_name = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_us = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jButton_Register = new javax.swing.JButton();
        jLabelRegistrazione = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jTextField_em = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel_titolo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_titolo.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_titolo.setText("LIMITED EVENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(jLabel_titolo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 1920, -1));

        jTextField_Fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FullnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 278, 39));

        jLabel_full_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_full_name.setText("Nome Completo");
        jPanel1.add(jLabel_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 200, 48));

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_username.setText("Username ");
        jPanel1.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 216, 33));

        jTextField_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 278, 39));

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_password.setText("Password ");
        jPanel1.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 216, 39));

        jPasswordField_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 278, 39));

        jButton_Register.setBackground(new java.awt.Color(51, 204, 0));
        jButton_Register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(0, 102, 0));
        jButton_Register.setText("REGISTRATI");
        jButton_Register.setMaximumSize(new java.awt.Dimension(107, 37));
        jButton_Register.setMinimumSize(new java.awt.Dimension(107, 37));
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 197, 45));

        jLabelRegistrazione.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelRegistrazione.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRegistrazione.setText(">> Hai già un account?Login! ");
        jLabelRegistrazione.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrazioneMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegistrazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 225, -1));

        jLabel_email.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_email.setText("Email ");
        jPanel1.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 216, -1));

        jTextField_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_em, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 278, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
      
     
      String fname = jTextField_Fullname.getText();
      String uname = jTextField_us.getText();
      String pass = String.valueOf(jPasswordField_pass.getPassword());
      String email = jTextField_em.getText();
     
      
      
      
      PreparedStatement ps;
      ResultSet rs;
      
      String query = "INSERT INTO utenti(nome_completo,username,password,email)" + "VALUES (?,?,?,?)";
      
     try{
          ps = MyConnection.getConnection().prepareStatement(query);   
          
          ps.setString(1,fname);
          ps.setString(2,uname);
          ps.setString(3,pass);
          ps.setString(4,email);
          
        
         
            
         
          if(ps.executeUpdate() > 0){
              JOptionPane.showMessageDialog(null,"Registrazione andata a buon fine");
              
          }else{
              JOptionPane.showMessageDialog(null,"Username già esistente");
             
          }
     }catch(SQLException ex){
        Logger.getLogger(Registrazione.class.getName()).log(Level.SEVERE,null,ex);
      
     }
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabelRegistrazioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrazioneMouseClicked
       Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrazioneMouseClicked

    private void jTextField_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emActionPerformed

    private void jPasswordField_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passActionPerformed

    private void jTextField_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usActionPerformed

    private void jTextField_FullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FullnameActionPerformed

    //create a function to check if the entred username already exits in the database
    
   /* public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM utenti WHERE username = ? ";
        
        try{
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                username_exist = true;
                
                JOptionPane.showMessageDialog(null,"Questo username è già stato scelto,Sceglierne un altro", "Username Fallito", 2);
                
            }
            
            
        }catch(SQLException ex){
            Logger.getLogger(Registrazione_Form.class.getName()).log(Level.SEVERE,null,ex);
        }
        return username_exist;
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabelRegistrazione;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_full_name;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_titolo;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JTextField jTextField_Fullname;
    private javax.swing.JTextField jTextField_em;
    private javax.swing.JTextField jTextField_us;
    // End of variables declaration//GEN-END:variables
}
